# Site settings
author: Alex Lazarev
title: 
header-img: img/home-bg.png
email: alex.m.lazarev@gmail.com
copyright_name: Alex Lazarev
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  a-laz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
